### PR TITLE
adding call to done function for async task

### PR DESCRIPTION
**Pull request by chuckcarpenter**
Adding a call to the done function so that the async task completes, as noted in the Grunt docs: 

http://gruntjs.com/creating-tasks#why-doesn-t-my-asynchronous-task-complete

### CODE REVIEW

**Comment by siverv** [comment]
This might cause problems if you test more than one file at once. Consider adding a check to see if all tests are finished, and perhaps warn grunt if a test fails:

```
---
 tasks/tasks.js | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/tasks/tasks.js b/tasks/tasks.js
index 96a2d18..ba3e1af 100644
--- a/tasks/tasks.js
+++ b/tasks/tasks.js
@@ -112,6 +112,7 @@ module.exports = function(grunt) {
             '\n-----------------------------------------------\n\n');

             grunt.log.error(str);
+            nofails = false;

           } else {
             grunt.log.ok('\n\n-----------------------------------------------' +
@@ -121,9 +122,16 @@ module.exports = function(grunt) {
             grunt.log.ok(str);
           }

+          testDone++;
+          if (testDone>=testTotal) {
+            done(nofails);
+          }
       });
     };

+    var testTotal = urls.length;
+    var testDone = 0;
+    var nofails = true;
     for (var i=0; i<urls.length; i++) {
       createPhantomRunner(i);
     }
-- 
```

**Comment by andyshora** [comment]
Thanks @siverv!

**Comment by chuckcarpenter** [comment]
@andyshora did you test with multiple files? I did and seemed okay, but wasn't sure if @siverv found a flaw.

**Comment by siverv** [comment]
It exits properly, but it's not telling grunt whether any tasks failed. By including a boolean parameter, you can utilize the the result outside of this grunt module, which seems to be the norm for grunt testing utilities.
Also (and this I am more uncertain of), by calling done() you allow grunt to continue even if there still are functions running. If this is the case, it could cause problems when testing multiple files, one file finishes before some others start _and_ the testing of the other files are affected by whatever grunt does next.

**Pull request merged**
