### PR TITLE
Add support for allowing additional Yslow option (custom CDNs, etc)

### PR DESCRIPTION
**Pull request by cnorthwood**

### CODE REVIEW

**Comment by andyshora** [comment]
@cnorthwood you absolute legend! I'll review and merge at the weekend. It really annoying when people rudely ask for me to add one liners here and there (that they could do themselves), but you Sir, were born a winner!

**Comment by cnorthwood** [comment]
No worries! Thanks for writing the plugin to start with, it saved me half the job to do what I wanted to do!

**Comment by bensquire** [comment]
@andyshora Any chance of getting this merged? I'd like to be able to specify an output format so that I can integrate with Jenkins (as per http://yslow.org/phantomjs/). Thanks @andyshora @cnorthwood

**Comment by andyshora** [comment]
Yes, sorry this one slipped! Done, cheers.

**Comment by geoffadams** [comment]
Noticed this version hasn't been pushed to npm, is it possible to get it up there?

**Comment by andyshora** [comment]
@geoffadams updated, if you update the npm package it should pull the latest:
https://www.npmjs.org/package/grunt-yslow

Cheers

**Comment by geoffadams** [comment]
Thanks, will give it a go in the morning!

**Pull request merged**
